--- #YAML:1.0
name:               Net-ParSCP
version:            0.05
abstract:           Parallel secure copy
author:
    - Casiano Rodriguez-Leon <casiano.rodriguez.leon@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Set::Scalar:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
