# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-ParSCP
version:      0.09
version_from: lib/Net/ParSCP.pm
installdirs:  site
requires:
    Set::Scalar:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
